server:
  port: 9000
spring:
    datasource:
      url: jdbc:h2:file:./.h2/pvnotedb
      driver-class-name: org.h2.Driver
      username: sa
      password: sa
      schema: classpath:db/schema.sql
      data: classpath:db/data.sql

    jpa:
      show-sql: true

      hibernate:
        ddl-auto: update
      database-platform: org.hibernate.dialect.H2Dialect
    h2:
      console:
        enabled: true
        path: /h2console
        settings:
          trace: false
          web-allow-others: false
    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      cache: false
      servlet:
        content-type: text/html
      enabled: true
      encoding: UTF-8
      mode: HTML
